### ISSUE TITLE
[Feature-request] Language selection and headphones bypass

### ISSUE THREAD

**Issue by d1nuc0m** [yuriykulikov/AlarmClock#336]
Hello,
I would like to propose a couple of new features:
* Language selection: make it possible for the user to select the language of the UI, instead of automatically setting it to system language
* Headphones bypass: allow the user to choose if play the alarm through the speakers even if headphones are connected to the device (sometimes it may happen to forget headphones/earphones connected and the alarm sound would be played through them)
Thank you for your attention

**Comment by yuriykulikov** [comment]
Hello,
unfortunately both these features cannot be implemented, because Android
does not allow this. Language is tied to System Language and it cannot be
bypassed in a meaningful way.
As for the headphones - applications simply do not know if headphones are
used or not. Application uses a certain audio stream. Android decides where
to route the sound.

**Comment by d1nuc0m** [comment]
Hello,
I thought it was possible as I had seen other apps doing that (Ghost Commander for language override and AVG's alarm clock for headphones override), thanks.

**Comment by yuriykulikov** [comment]
Both will be, of course, theoretically possible. But it is a lot of effort. Total commander is not an actual Android App, it is more like a port of a crossplatform app. It probably doesn't use Android language feature anyway.

As for the headphones, these kind of issues are so hard to handle on Android that I won't commit myself to implementing this. It will be so much effort and I have very limited resources. Sorry.
