### ISSUE TITLE
Replace Toast with a snackbar

### ISSUE THREAD

**Issue by yuriykulikov** [yuriykulikov/AlarmClock#352]
# Replace Toast with a snackbar

## Summary

Replace invasive out-of-style Toast with a nice non-intrusive snackbar if the UI is visible. Fall back to the Toast if not (e.g. dismissed from a notification).

## Motivation

Toast draws over the FAB and InfoBar and has bright background which doesn't go well with dark themes.

## Description

If UI is visible, show a snackbar.
If UI is not visible, show the Toast (present behavior).

## Drawbacks, risks and assumptions

Snackbar will be less visible, it will also cost quite some time to get it right from the design perspective.
### Remove Toast completely
Simple, but this removes valuable information which is useful to detect accidental incorrect repeats times.

### Use the info bar
Reusing the InfoBar is easy to implement. But this will be very hard to spot for the user. Perhaps an accent color can be used to counter this issue.

### Only show toast when UI is not visible
User won't be notified at all about the time when alarm is scheduled.

### Keep the toast
We can, of course, keep the current behavior, but toast overlapping the FAB really doesn't look nice.

**Comment by kolanse** [comment]
Hi , can i work on this feature @yuriykulikov

**Comment by yuriykulikov** [comment]
Sure, but please branch off my 'redesign' branch

**Comment by kolanse** [comment]
Alright sure thank you

**Comment by kolanse** [comment]
Hi i wanted to ask a question to gain a better understanding of what you meant by if the ui is visible. 
![WhatsApp Image 2021-07-19 at 23 04 19](https://user-images.githubusercontent.com/68715929/126233710-0748e690-53b6-4c85-be21-c1a352bc45bc.jpeg)
Right now this is the toast that is showing on the screen. Your reference to a visible ui does it mean when the alarm list is large enough that a toast covers the info

**Comment by yuriykulikov** [comment]
By "UI visible" I meant that the App UI is on screen. For example, if you
dismiss the alarm for a notification, the App UI is not visible.

**Comment by kolanse** [comment]
@yuriykulikov  So i worked on the designs and i wanted to share it with you before making a PR to see whether it would be nice
![WhatsApp Image 2021-07-22 at 22 37 09 (4)](https://user-images.githubusercontent.com/68715929/126720623-b3b1293c-5911-426c-9149-785c01735f8c.jpeg)
![WhatsApp Image 2021-07-22 at 22 37 09 (3)](https://user-images.githubusercontent.com/68715929/126720626-3246c942-5eb6-41fb-82ec-929cff9b1588.jpeg)
![WhatsApp Image 2021-07-22 at 22 37 09 (2)](https://user-images.githubusercontent.com/68715929/126720630-6095dd83-099a-4502-b930-ff5dbaa0ddd5.jpeg)
![WhatsApp Image 2021-07-22 at 22 37 09 (1)](https://user-images.githubusercontent.com/68715929/126720633-050fad71-4abb-41ff-9b94-020b5e3c9168.jpeg)
![WhatsApp Image 2021-07-22 at 22 37 09](https://user-images.githubusercontent.com/68715929/126720638-9b372a95-d348-482a-b45c-37b4f946a97e.jpeg)


Also for the formatText function that is inside the toast presenter class . do you think it would be nice for me to abstract it out of the class because the snackbar also needs access to it

**Comment by yuriykulikov** [comment]
Looks great!

The function can be moved elsewhere, of course.

**Comment by kolanse** [comment]
Alright let me work on abstracting it so that i can make a pr. The pr should be to Redesign right ?

**Comment by yuriykulikov** [comment]
Yes!

**Comment by kolanse** [comment]
@yuriykulikov  i have made a PR

**Comment by yuriykulikov** [comment]
@kolanse thank you! I have made some comments, a few changes would be nice before this is merged. Please take a look :)

**Comment by kolanse** [comment]
@yuriykulikov  Alright thank you . i will look into it and make the fixes

**Comment by yuriykulikov** [comment]
@kolanse I think we can show the snackbar also when enabling the alarm. Would you like to give it a try?

**Comment by yuriykulikov** [comment]
@kolanse I have changed the snackbar to be shown every time when the alarm is changed.
