### ISSUE TITLE
Question : How to set default Fade-in time?

### ISSUE THREAD

**Issue by lune856** [yuriykulikov/AlarmClock#440]
Thanks for such an amazing open-source app. I'm studying this app in order to learn the mechanism of an alarm clock app. Upon reviewing some settings, it was difficult for me to apprehend setting default preference values. 

I've checked Prefs.kt where (at line 56) we have what seems like the default value, 

`fadeInTimeInSeconds = factory.intStringDataStore(KEY_FADE_IN_TIME_SEC, 30)`

However, changing this to (say 10) won't update the preference itself. When opened preference it still says 'Fade-in duration is 30 seconds' 
Any input will be very helpful. Thanks again for such an amazing app.

**Comment by lune856** [comment]
Just realized editing the default value inside Preferences.xml (under Resources) and Prefs.kt will do the job (Re-install seems necessary thought).

**Comment by yuriykulikov** [comment]
Hello,
Yes, preferences.xml is currently the way to change default settings. The
reason for this is compatibility and me being lazy 🙂 Of course, it would
be much cleaner to have defaults in one place (Prefs.kt), but preferences
fragment relies on preference values being already set in the shared
preferences. A proper way of doing that would be to rewrite preferences
fragment so that all values come from Prefs.kt, not directly from shared
preferences.

Cheers
